name: Merge
on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:
jobs:
  merge:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_REPOSITORY: wandenberg/nginx-push-stream-module
        uses: rekgrpth/git-fetch-upstream-merge-push-shell-action@v1
  dispatch:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          INPUTS_CLIENT_PAYLOAD: '{"repository":${{ toJson(github.event.repository.name) }}}'
          INPUTS_EVENT_TYPE: latest
          INPUTS_REPOSITORY: ${{ github.repository_owner }}/${{ matrix.repo }}
        uses: rekgrpth/github-repository-dispatch-shell-action@v1
    strategy:
      matrix:
        repo:
          - nginx.docker
